// <auto-generated />
using Instructors.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Instructors.WebApi.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190613204912_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Instructors.WebApi.Data.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new { Id = 1, FirstName = "Michelangelo", LastName = "Buonarroti", MiddleName = "" },
                        new { Id = 2, FirstName = "Leonardo", LastName = "da Vinci", MiddleName = "" },
                        new { Id = 3, FirstName = "Vandinelli", LastName = "Bartolommeo", MiddleName = "" },
                        new { Id = 4, FirstName = "Lorenzo", LastName = "Ghiberti", MiddleName = "" },
                        new { Id = 5, FirstName = "Benvenuto", LastName = "Cellini", MiddleName = "" },
                        new { Id = 6, FirstName = "Bernando", LastName = "Rossellino", MiddleName = "" },
                        new { Id = 7, FirstName = "Guido", LastName = "Mazzoni", MiddleName = "" },
                        new { Id = 8, FirstName = "Pietro", LastName = "Torrigiano", MiddleName = "" },
                        new { Id = 9, FirstName = "Diego", LastName = "Siloe", MiddleName = "" },
                        new { Id = 10, FirstName = "Matteo", LastName = "Civitali", MiddleName = "" },
                        new { Id = 11, FirstName = "Viet", LastName = "Stoss", MiddleName = "" },
                        new { Id = 12, FirstName = "Alessandro", LastName = "Vittoria", MiddleName = "" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
